### ISSUE TITLE
Error: Zeile 455: Partimagelist ist nicht gesetzt.

### ISSUE THREAD

**Issue by holgerd001** [mviereck/microscopy-tools#2]
Hi,
I tried imfuse for the first time with a stack of 7 images. -> It works.
Then I tried with a stack of 73 Images:
imfuse aborted and I got the message "Zeile 455: Partimagelist ist nicht gesetzt."

Both times i started with "imfuse -o imfu_diff.tif --cache --diffstat aligned_C_m_c100_order_00??.tif" (or similar).

Greetings from snowy part of Germany
Holger

**Comment by holgerd001** [comment]
I forgot the version: imfuse v0.6.0-beta

**Comment by mviereck** [comment]
Thank you for the report! I've uploaded a fixed version yet.

And thank you for testing imfuse! I am happy to get some feedback. Please let me know if it does its job well for you or where results are not satisfying. I am still exploring possibilities and setups.

Greeting from Germany, too ;-)
Martin

**Comment by holgerd001** [comment]
Thanks for fixing. Now it works. But the quality is poor. But i have no experiences with imfuse. I'll try different parameters.

I'm using align_image_stack and enfuse for stacking and fusing macro an micro photos. But both are very slow. So I'm looking for a faster alternative and found imfuse. I'm not a mathematician, so it's not easy for me to understand how they are working and finding good parameters.

...
I just let imfuse work with 72 images (of an insect). It takes a lot of memory (14.xGB and 2.xGB swap) and all cpu time.

The advantage of align_image_stack and enfuse is, that they left enough memory and cpu time to do 'normal' work like writing this comment.
Ok but one after the other. Now I'll take a smaller stack of a moth and use align_image_stack, enfuse and imfuse.

BTW: what's a good workflow in your opinion?
1. take photos
2. align them (align_image_stack)
3. fuse them (enfuse or imfuse)
4. convert tif to jpg (magick)
5. transfer exif data (exiftool)


Greetings
Holger

**Comment by mviereck** [comment]
Thank you for the feedback!

> But both are very slow. So I'm looking for a faster alternative and found imfuse.

I have to admit that imfuse will be even slower than enfuse.
A pretty fast all-in-one solution is https://github.com/PetteriAimonen/focus-stack
It has a few drawbacks, but is worth a look.
It provides a pretty fast alignment option; but it leaves [artefacts at the image borders](https://github.com/PetteriAimonen/focus-stack/issues/9#issuecomment-749361411). 

align_image_stack is very slow at big stacks because it aligns all images at once instead of doing it stepwise.
stackfuser provides an option to use align_image_stack much faster. 

> It takes a lot of memory (14.xGB and 2.xGB swap)
> The advantage of align_image_stack and enfuse is, that they left enough memory and cpu time to do 'normal' work like writing this comment.

I am surprised. How big  are your source images (in pixel)?
I've uploaded a commit that uses less threads at once and also allows to specify the number of threads with option `--threads N`. 
imfuse uses all available CPU power; but it runs the expensive commands with `nice`, so other applications are preferred by the kernel if they need CPU power, too. 
Likely only the swap usage is slowing down your system. With less threads now ( and thus less memory usage) your system should be usable again while imfuse is running.

imfuse should do better checks for memory usage automatically.

> BTW: what's a good workflow in your opinion?

Your workflow looks right. Not sure what you mean with `transfer exif data`, just noting some data about copyright, date etc?
If the images are very big (e.g. 6000x4000), I recommend to shrink them down to e.g. 600x400. Try to find well parameter sets with the small images. Once the result is fine, you can run again with big images.
Instead of shrinking down, you could crop a small part of the images and run test setups with the cropped parts.

If your source images are jpg, I recommend to convert to tif before doing anything else. Convert the final stacked tif result to jpg for publishing online only.

stackfuser aims to help in this workflow.

> I'm not a mathematician, so it's not easy for me to understand how they are working and finding good parameters.

In folder `fuse_sets` you find a lot of examples for imfuse parameters: https://github.com/mviereck/microscopy-tools/tree/master/fusesets
For macro images look at https://github.com/mviereck/microscopy-tools/blob/master/fusesets/macro-soft-less
I recommend for macro:
```
imfuse --log=s0.2  --soft=25
```
If some foreground objects are overwritten by background objects, try the slower but more accurate:
```
imfuse --log=s0.2 --close=2x2 --soft=25 --less=4
```
Also add options `-vV` to see what is going on.
If you add option `--cache`, imfuse can re-use some files across several test setups. This can speed up further test runs. Delete folder `cache.imfuse` manually once you are done.

**Comment by holgerd001** [comment]
>I have to admit that imfuse will be even slower than enfuse.
It's a pity.

>A pretty fast all-in-one solution is https://github.com/PetteriAimonen/focus-stack
I tried to install, but failed. It's made for debian and I use opensuse. As far as I figured out there are some difference in some libs.

>stackfuser provides an option to use align_image_stack much faster.
Thanks, I'll test it next time.

>I am surprised. How big are your source images (in pixel)?
I used align_image_stack with option -C, so the it will differ a little bit around 4.400x2.900px.

> ... with option --threads N
Ok, I'll test it.

> Not sure what you mean with transfer exif data
The exif data (like, exposure time, Fnumber, ISO, ...) get lost. I transfer it from the first JPG to the stacked image.
(e.g. exiftool -overwrite_original -tagsfromfile D2030892.JPG -all:all xD2030892_aligned_C_m_c40_order_grayl-star.jpg)

>  I recommend to shrink them down
I've done now, but run into a problem:

> imfuse -o imfu_diffr2clo2x2_soft25_less5.tif --cache --diffstat=r2,close2x2 --soft=25 --less=5 pc20-aligned_C_m_c40_order_00??.tif
imfuse note: Setting --output=/mnt/Daten/holger/Fotos/stacks/20210203_Motte4_Kopf_Mikroskopobj/imfu_diffr2clo2x2_soft25_less5.tif
rm: das Entfernen von '/mnt/Daten/holger/Fotos/stacks/20210203_Motte4_Kopf_Mikroskopobj/cache.imfuse/*NUMBER*' ist nicht möglich: Datei oder Verzeichnis nicht gefunden
enfuse: info: loading next image: /mnt/Daten/holger/Fotos/stacks/20210203_Motte4_Kopf_Mikroskopobj/pc20-aligned_C_m_c40_order_0021.tif 1/1
enfuse: info: loading next image: /mnt/Daten/holger/Fotos/stacks/20210203_Motte4_Kopf_Mikroskopobj/pc20-aligned_C_m_c40_order_0020.tif 1/1
enfuse: info: loading next image: /mnt/Daten/holger/Fotos/stacks/20210203_Motte4_Kopf_Mikroskopobj/pc20-aligned_C_m_c40_order_0019.tif 1/1
enfuse: info: loading next image: /mnt/Daten/holger/Fotos/stacks/20210203_Motte4_Kopf_Mikroskopobj/pc20-aligned_C_m_c40_order_0018.tif 1/1
enfuse: info: loading next image: /mnt/Daten/holger/Fotos/stacks/20210203_Motte4_Kopf_Mikroskopobj/pc20-aligned_C_m_c40_order_0017.tif 1/1
enfuse: info: loading next image: /mnt/Daten/holger/Fotos/stacks/20210203_Motte4_Kopf_Mikroskopobj/pc20-aligned_C_m_c40_order_0016.tif 1/1
enfuse: info: loading next image: /mnt/Daten/holger/Fotos/stacks/20210203_Motte4_Kopf_Mikroskopobj/pc20-aligned_C_m_c40_order_0015.tif 1/1
enfuse: info: loading next image: /mnt/Daten/holger/Fotos/stacks/20210203_Motte4_Kopf_Mikroskopobj/pc20-aligned_C_m_c40_order_0014.tif 1/1
enfuse: info: loading next image: /mnt/Daten/holger/Fotos/stacks/20210203_Motte4_Kopf_Mikroskopobj/pc20-aligned_C_m_c40_order_0013.tif 1/1
enfuse: info: loading next image: /mnt/Daten/holger/Fotos/stacks/20210203_Motte4_Kopf_Mikroskopobj/pc20-aligned_C_m_c40_order_0012.tif 1/1
enfuse: info: loading next image: /mnt/Daten/holger/Fotos/stacks/20210203_Motte4_Kopf_Mikroskopobj/pc20-aligned_C_m_c40_order_0011.tif 1/1
enfuse: info: loading next image: /mnt/Daten/holger/Fotos/stacks/20210203_Motte4_Kopf_Mikroskopobj/pc20-aligned_C_m_c40_order_0010.tif 1/1
enfuse: info: loading next image: /mnt/Daten/holger/Fotos/stacks/20210203_Motte4_Kopf_Mikroskopobj/pc20-aligned_C_m_c40_order_0009.tif 1/1
enfuse: info: loading next image: /mnt/Daten/holger/Fotos/stacks/20210203_Motte4_Kopf_Mikroskopobj/pc20-aligned_C_m_c40_order_0008.tif 1/1
enfuse: info: loading next image: /mnt/Daten/holger/Fotos/stacks/20210203_Motte4_Kopf_Mikroskopobj/pc20-aligned_C_m_c40_order_0007.tif 1/1
enfuse: info: loading next image: /mnt/Daten/holger/Fotos/stacks/20210203_Motte4_Kopf_Mikroskopobj/pc20-aligned_C_m_c40_order_0006.tif 1/1
enfuse: info: loading next image: /mnt/Daten/holger/Fotos/stacks/20210203_Motte4_Kopf_Mikroskopobj/pc20-aligned_C_m_c40_order_0005.tif 1/1
enfuse: info: loading next image: /mnt/Daten/holger/Fotos/stacks/20210203_Motte4_Kopf_Mikroskopobj/pc20-aligned_C_m_c40_order_0004.tif 1/1
enfuse: info: loading next image: /mnt/Daten/holger/Fotos/stacks/20210203_Motte4_Kopf_Mikroskopobj/pc20-aligned_C_m_c40_order_0003.tif 1/1
enfuse: info: loading next image: /mnt/Daten/holger/Fotos/stacks/20210203_Motte4_Kopf_Mikroskopobj/pc20-aligned_C_m_c40_order_0002.tif 1/1
enfuse: info: loading next image: /mnt/Daten/holger/Fotos/stacks/20210203_Motte4_Kopf_Mikroskopobj/pc20-aligned_C_m_c40_order_0001.tif 1/1
 --soft '25' --lessthanmax '5' --output '/mnt/Daten/holger/Fotos/stacks/20210203_Motte4_Kopf_Mikroskopobj/cache.imfuse/imfuseimfuse.diffstat=r2-close2x2-median-mean_soft25_less5_bg=enfuse.151832.tif' --
magick: insufficient image data in file `/mnt/Daten/holger/Fotos/stacks/20210203_Motte4_Kopf_Mikroskopobj/cache.imfuse/montage-diffstat-soft25-less5.98d67c.tif' @ error/tiff.c/ReadTIFFImage/1774.
imfuse ERROR: Error while cutting images

magick: insufficient image data in file `/mnt/Daten/holger/Fotos/stacks/20210203_Motte4_Kopf_Mikroskopobj/cache.imfuse/montage-diffstat-soft25-less5.98d67c.tif' @ error/tiff.c/ReadTIFFImage/1774.

If I use the full size images, it works. Shall I open a new issue?

> In folder fuse_sets you find a lot of examples 
Thanks for that advice. I'll try some of these examples.


Greetings
Holger

**Comment by mviereck** [comment]
> I used align_image_stack with option -C, so the it will differ a little bit around 4.400x2.900px.

That should not cause too much memory usage. I've tried with even greater images around 6000x400px and had no memory issue (16 GB RAM in total).
The number of images does not matter in general. imfuse only works at one image at a time, having about 2 or three more images of same size in RAM for mask comparision etc.

It does matter in two cases where many images are load at once:
 - Generating a background with enfuse. enfuse crashes here with the debian version if there is not enough memory. I'll try to build a static version with hard disk caching enabled.
 - Generating a min or max image. If there is not enough memory, imfuse splits the images in multiple parts. I'll check that again.

> The exif data (like, exposure time, Fnumber, ISO, ...) get lost. I transfer it from the first JPG to the stacked image.
(e.g. exiftool -overwrite_original -tagsfromfile D2030892.JPG -all:all xD2030892_aligned_C_m_c40_order_grayl-star.jpg)

I should include this in imfuse and stackfuser, thank you for the example!

> magick: insufficient image data in file `/mnt/Daten/holger/Fotos/stacks/20210203_Motte4_Kopf_Mikroskopobj/cache.imfuse/montage-diffstat-soft25-less5.98d67c.tif' @ error/tiff.c/ReadTIFFImage/1774.

> If I use the full size images, it works. Shall I open a new issue?

That's odd. Is it possible that one of the shrinked source images is corrupted? Though, in that case I would have expected a failure earlier. Would you provide me the images so I can test myself? (A new ticket makes sense.)

**Comment by holgerd001** [comment]
> That should not cause too much memory usage
Ok, I keep it in mint. Perhaps there was an other task in background which causes the mem consumption.

... some minutes later

imfuse v0.6.1-beta

imfuse -o imfu_diffr5_soft10_contr1.tif --diffstat=r5 --soft=10 --contrast=1 aligned_C_m_c40_order_00??.tif

21 files "aligned_C_m_c40_order_00??.tif" with 4.495x2.987px

It takes temporary nearly 100% cpu time of all cpus (older i7) and 10GB mem of 16GB.

**Comment by mviereck** [comment]
> It takes temporary nearly 100% cpu time of all cpus (older i7) and 10GB mem of 16GB.

With option `--soft` imfuse generates a background image with `enfuse`. This might cause the high load and cannot be regulated by imfuse.
Furthermore, imfuse combines all masks at once in some steps. That can cause high memory usage for big images. I've set the default from max. 95% RAM down to max. 80%. I'll add an option to set this manually.

I've added some more messages to see the current step imfuse is working on. With option `--verbose` (and maybe `--showimage`, together `-vV`) you'll see more details.
You could check the output of `top` to see which progress is currently running high.

> It takes temporary nearly 100% cpu time of all cpus (older i7) and 10GB mem of 16GB.

The system should work well nonetheless because imfuse sets down the process priority with command `nice`. If you have high swap usage although there is enough free RAM, you could reduce the 'swapiness' of the system.

Edit: btw, imfuse now transfers the exif metadata from the first source image to the result. In stackfuser I'll include this later. Thanks for the suggestion!

**Comment by holgerd001** [comment]
> The system should work well nonetheless because imfuse sets down the process priority with command `nice`. If you have high swap usage although there is enough free RAM, you could reduce the 'swapiness' of the system.
The systemmonitor tells me all cpus are in use (100%), but I can do normal work. That's ok.

> Edit: btw, imfuse now transfers the exif metadata from the first source image to the result. In stackfuser I'll include this later. Thanks for the suggestion!
Hm, that doesn't help in my case. The tif-files generated by align_image_stack don't have the exif data like the JPGs.

To check, if the exif data will be transferred I put it to the generated tif files and started imfuse. But that was not the best idea. I got lots of warnings like this:
imfuse -o imfu_diffr5_aligned_C_m_c40_order.tif --verbose --diffstat=r5 aligned_C_m_c40_order_00??.tif

imfuse note: Setting --output=/mnt/Daten/holger/Fotos/stacks/20210203_Motte4_Kopf_Mikroskopobj/imfu_diffr5_aligned_C_m_c40_order.tif

imfuse: Mask options:
NUM=1,METHOD=diffstat,r=5,WORD1=median,WORD2=mean,LEVEL,TYPE=mask

magick: Unknown field with tag 50341 (0xc4a5) encountered. `TIFFReadDirectory' @ warning/tiff.c/TIFFWarnings/1006.
magick: Unknown field with tag 34864 (0x8830) encountered. `TIFFReadCustomDirectory' @ warning/tiff.c/TIFFWarnings/1006.
magick: Wrong data type 3 for "PixelXDimension"; tag ignored. `TIFFReadCustomDirectory' @ warning/tiff.c/TIFFWarnings/1006.
magick: Wrong data type 3 for "PixelYDimension"; tag ignored. `TIFFReadCustomDirectory' @ warning/tiff.c/TIFFWarnings/1006.
magick: Incompatible type for "FileSource"; tag ignored. `TIFFFetchNormalTag' @ warning/tiff.c/TIFFWarnings/1006.
magick: Wrong data type 3 for "GainControl"; tag ignored. `TIFFReadCustomDirectory' @ warning/tiff.c/TIFFWarnings/1006.
magick: Unknown field with tag 42034 (0xa432) encountered. `TIFFReadCustomDirectory' @ warning/tiff.c/TIFFWarnings/1006.
magick: Unknown field with tag 42036 (0xa434) encountered. `TIFFReadCustomDirectory' @ warning/tiff.c/TIFFWarnings/1006.
magick: Unknown field with tag 50341 (0xc4a5) encountered. `TIFFReadDirectory' @ warning/tiff.c/TIFFWarnings/1006.
magick: Unknown field with tag 50341 (0xc4a5) encountered. `TIFFReadDirectory' @ warning/tiff.c/TIFFWarnings/1006.
magick: Unknown field with tag 34864 (0x8830) encountered. `TIFFReadCustomDirectory' @ warning/tiff.c/TIFFWarnings/1006.
magick: Wrong data type 3 for "PixelXDimension"; tag ignored. `TIFFReadCustomDirectory' @ warning/tiff.c/TIFFWarnings/1006.
magick: Wrong data type 3 for "PixelYDimension"; tag ignored. `TIFFReadCustomDirectory' @ warning/tiff.c/TIFFWarnings/1006.

And the exif data were not transferred.

Where are the exif data expected?

**Comment by mviereck** [comment]
> And the exif data were not transferred.

> Where are the exif data expected?

Edit:

They should be in the final output image. I've made another fix yet, maybe it got lost in one last step.
Now the exif data seems to be transferred correctly.
The Orientation tag is removed because it can cause issues in some image processing.
stackfuser now preserves the exif data, too, across all steps like align etc.

> To check, if the exif data will be transferred I put it to the generated tif files and started imfuse. But that was not the best idea. I got lots of warnings like this:

I've added IM option `-quiet` to suppress the warnings. It normally prints them if it reads metadata tags it does not know.

**Comment by holgerd001** [comment]
> Now the exif data seems to be transferred correctly.
Yes, that's what I see too.

1. Put exif to the aligned images
exiftool -overwrite_original -tagsfromfile D2030892.JPG -all:all aligned_C_m_c40_order_00??.tif

2. using imfuse
imfuse -o imfu_morphologyr2_aligned_C_m_c40_order.tif --verbose --morphology=r2 aligned_C_m_c40_order_00??.tif
Non of the irritating warnings came up.

3. Checking exif in imfu_morphologyr2_aligned_C_m_c40_order.tif
The file contains the exif data.

It works!

**Comment by mviereck** [comment]
> It works!

Great!
I think I can close this multi-topic ticket now.

Please open as much tickets as you like, including test setups.
I am exploring useful option combinations, too, and it helps to get some feedback.

**Comment by mviereck** [comment]
I've added an explicit `--exif` option to imfuse, please have a look at #5 .
